"""Add telegram_bots table

Revision ID: 1690e658bdd6
Revises: 15c61425fee7
Create Date: 2025-06-12 16:23:20.094778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1690e658bdd6'
down_revision: Union[str, None] = '15c61425fee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bot_token', sa.String(), nullable=False),
    sa.Column('bot_username', sa.String(), nullable=True),
    sa.Column('bot_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_token'),
    sa.UniqueConstraint('bot_username')
    )
    with op.batch_alter_table('telegram_bots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_bots_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_bots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_bots_id'))

    op.drop_table('telegram_bots')
    # ### end Alembic commands ###
